version: '3.8'

services:
  api:
    build: .
    container_name: nest_api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:admin@localhost:3306/user_management
      - JWT_SECRET=minha-chave-secreta
      - JWT_EXPIRES_IN=1h
      - NODE_ENV=development
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npx prisma generate && npm run build && npm run start"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestdb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
